merge master command

diff --git a/gitconfig b/gitconfig
--- a/gitconfig
+++ b/gitconfig
@@ -77,6 +77,17 @@
         VAR=$1; OLD=$2; NEW=$3; shift 3; \
         git filter-branch --env-filter \"if [ \\\"$`echo $VAR`\\\" = '$OLD' ]; then export $VAR='$NEW'; fi\" $@; \
     }; f"
+    mm = "!f() { \
+        current_branch=$(git rev-parse --abbrev-ref HEAD); \
+        if [ \"$current_branch\" = \"master\" ]; then \
+            echo 'Error: You are already on the master branch'; \
+            exit 1; \
+        fi; \
+        git checkout master; \
+        git merge $current_branch; \
+        git push origin master; \
+        git checkout $current_branch; \
+    }; f"
 
 [core]
     excludesfile = ~/.gitignore_global
